name: hella_infra_app
description: A bond trading app for Hella Infra.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State management
  flutter_bloc: ^8.1.3
  # Dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.2
  # Code generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  # Network
  dio: ^5.3.2
  internet_connection_checker: ^1.0.0+1
  # UI
  fl_chart: ^0.63.0
  shimmer: ^3.0.0
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1
  haptic_feedback: ^0.5.1+1
  # Share and Social
  share_plus: ^7.1.0
  url_launcher: ^6.1.14
  # PDF generation
  pdf: ^3.10.4
  path_provider: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  # Code generation
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.1
  # Testing
  bloc_test: ^9.1.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true
